test_blog/blog/urls.py
#!/user/bin/env python3
# -*- coding: utf-8 -*-
"""
__author__ = 'Karas'
__time__ = '2021/6/10 11:20'
"""
from django.urls import path, re_path
from . import views

app_name = 'blog'

urlpatterns = [
    path('test_ckeditor_front/', views.test_ckeditor_front),
    path('', views.indexview.as_view(), name='index'),
    path('registe/', views.registe, name='registe'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    re_path('blog/(?P<pk>[0-9]+)/', views.blogdetailview.as_view(), name='detail'),
    re_path('category/(?P<pk>[0-9]+)/', views.categoryview.as_view(), name='category'),
    re_path('tag/(?P<pk>[0-9]+)/', views.tagview.as_view(), name='tag'),
    re_path('archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/', views.archives, name='archives'),
    path('myindex/<int:loguserid>/', views.myindex.as_view(), name='myindex'),
    path('authorindex/<int:id>/', views.authorindex.as_view(), name='authorindex'),
]

test_blog/comments/urls.py
#!/user/bin/env python3
# -*- coding: utf-8 -*-
"""
__author__ = 'Karas'
__time__ = '2021/6/15 15:31'
"""
from django.urls import path
from . import views

app_name = 'comments'
urlpatterns = [
    path('comment/post/<int:blog_pk>/', views.blog_comment, name="blog_comment"),
]

test_blog/test_blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('comments/', include('comments.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('search/', include('haystack.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test_blog/blog/models.py
from django.db import models

# Create your models here.
from django.urls import reverse
# from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.html import strip_tags
from django.contrib.auth.models import AbstractUser

class loguser(AbstractUser):
    nikename = models.CharField(max_length=32, verbose_name="昵称", blank=True)
    telephone = models.CharField(max_length=11, null=True, unique=True)
    head_img = models.ImageField(upload_to='headimage', blank=True, null=True, verbose_name="头像")
    def __str__(self):
        return self.username

    class Meta:
        verbose_name = "用户信息表"
        verbose_name_plural = verbose_name

class Category(models.Model):
    name = models.CharField(max_length=32, verbose_name="分类名")
    des = models.CharField(max_length=100, verbose_name="备注", null=True)
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = '分类'

class Tag(models.Model):
    name = models.CharField(max_length=32, verbose_name="标签名")
    des = models.CharField(max_length=100, verbose_name="备注", null=True)
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = "标签"


class Blog(models.Model):
    title = models.CharField(max_length=70, verbose_name="文章标题")
    body = RichTextUploadingField(verbose_name="文本内容")
    created_time = models.DateTimeField(verbose_name="创建时间")
    modified_time = models.DateTimeField(verbose_name="修改时间")
    excerpt = models.CharField(max_length=200, blank=True, verbose_name="文章摘要")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="分类")
    tags = models.ManyToManyField(Tag, blank=True, verbose_name="标签")
    author = models.ForeignKey(loguser, on_delete=models.CASCADE, verbose_name="作者")
    views = models.IntegerField(default=0, verbose_name="查看次数")

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def save(self, *args, **kwargs):
        if not self.excerpt:
            self.excerpt = strip_tags(self.body)[:118]
            super(Blog, self).save(*args, **kwargs)
        else:
            super(Blog, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_time']
        verbose_name = "文档管理表"
        verbose_name_plural = "文档管理表"

test_blog/comments/models.py
from django.db import models

# Create your models here.

class Comment(models.Model):
    name = models.CharField(max_length=32)
    email = models.EmailField(max_length=60)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    blog = models.ForeignKey('blog.Blog', on_delete=models.CASCADE,)

    def __str__(self):
        return self.text[:20]

test_blog/blog/forms.py
#!/user/bin/env python3
# -*- coding: utf-8 -*-
"""
__author__ = 'Karas'
__time__ = '2021/6/10 17:54'
"""
from django import forms
from . import models
from django.core.exceptions import ValidationError

class reg_form(forms.Form):
    username = forms.CharField(
        max_length=20,
        label="登录账号",
        error_messages={
            'max_length': '登录账号不能超过20位',
            'required': '登录账号不能为空'
        },
        widget=forms.widgets.TextInput(
            attrs={'class': 'form-control'},
        )
    )
    password = forms.CharField(
        min_length=6,
        label="密码",
        error_messages={
            'min_length': '密码最少6位',
            'required': '密码不能为空',
        },
        widget=forms.widgets.PasswordInput(
            attrs={'class': 'form-control'},
            render_value=True,
        )
    )
    repassword = forms.CharField(
        min_length=6,
        label="确认密码",
        error_messages={
            'min_length': '密码最少6位',
            'required': '密码不能为空',
        },
        widget=forms.widgets.PasswordInput(
            attrs={
                'class': 'form-control'
            },
            render_value=True,
        )
    )
    nikename = forms.CharField(
        max_length=20,
        required=False,
        label="姓名",
        error_messages={
            'max_length': '姓名长度不能超过20位',

        },
        initial='无名氏',
        widget=forms.widgets.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    email = forms.EmailField(
        label='邮箱',
        error_messages={
            'invalid': '邮箱格式不对',
            'required': '邮箱不能为空',
        },
        widget=forms.widgets.EmailInput(
            attrs={'class': 'form-control',}
        )
    )
    telephone = forms.CharField(
        max_length=11,
        label="电话号码",
        required=False,
        error_messages={
            'max_length': '最大长度不超过11位',
        },
        widget=forms.widgets.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    head_img = forms.ImageField(
        label='头像',
        widget=forms.widgets.FileInput(
            attrs={'style': 'display:none'}
        )
    )

    def clean_username(self):
        uname = self.cleaned_data.get('username')
        vexist = models.loguser.objects.filter(username=uname)
        if vexist:
            self.add_error('username', ValidationError('登录账号已存在！'))
        else:
            return uname

    def clean_repassword(self):
        password = self.cleaned_data.get('password')
        repassword = self.cleaned_data.get('repassword')
        if repassword and repassword != password:
            self.add_error('repassword', ValidationError('两次输入的密码不一致'))
        else:
            return repassword

test_blog/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from . import models
from django.contrib.auth.models import auth
from . import forms
from comments.forms import CommentForm
from django.views.generic import DetailView, ListView
# Create your views here.

def test_ckeditor_front(request):
    user_obj = models.loguser.objects.all().first()
    auth.login(request, user_obj)
    blog = models.Blog.objects.get(id=1)
    return render(request, 'blog/test_ckeditor_front.html', {'blog': blog})

def registe(request):
    if request.method == 'POST':
        form_obj = forms.reg_form(request.POST, request.FILES)
        if form_obj.is_valid():
            form_obj.cleaned_data.pop('repassword')
            user_obj = models.loguser.objects.create_user(**form_obj.cleaned_data, is_staff=1, is_superuser=1)
            auth.login(request, user_obj)
            return redirect('/')
        else:
            return render(request, 'blog/registe.html', {'formobj': form_obj})
    form_obj = forms.reg_form()
    return render(request, 'blog/registe.html', {'formobj': form_obj})


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        pwd = request.POST.get('password')
        user = auth.authenticate(username=username, password=pwd)
        if user:
            auth.login(request, user)
            return redirect('/')
        else:
            errormsg = '用户名或密码错误！'
            return render(request, 'blog/login.html', {'error': errormsg})
    return render(request, 'blog/login.html')



class categoryview(ListView):
    model = models.Blog
    template_name = 'blog/index.html'
    context_object_name = 'blog_list'
    def get_queryset(self):
        cate = get_object_or_404(models.Category, pk=self.kwargs.get('pk'))
        return super(categoryview, self).get_queryset().filter(category=cate).order_by('-created_time')

class tagview(ListView):
    model = models.Blog
    template_name = 'blog/index.html'
    context_object_name = 'blog_list'
    def get_queryset(self):
        tag = get_object_or_404(models.Tag, pk=self.kwargs.get('pk'))
        return super(tagview, self).get_queryset().filter(tags=tag).order_by('created_time')

def archives(request, year, month):
    blog_list = models.Blog.objects.filter(created_time__year=year, created_time__month=month).order_by('-created_time')
    return render(request, 'blog/index.html', context={'blog_list': blog_list})


class myindex(ListView):
    model = models.Blog
    template_name = 'blog/index.html'
    context_object_name = 'blog_list'
    def get_queryset(self):
        loguser = get_object_or_404(models.loguser, pk=self.kwargs.get('loguserid'))
        return super(myindex, self).get_queryset().filter(author=loguser).order_by('-created_time')

    def get_context_data(self, **kwargs):
        context = super(myindex, self).get_context_data(**kwargs)
        context['tabname'] = 'mytab'
        return context

def logout(request):
    auth.logout(request)
    return redirect('/')

class indexview(ListView):
    model = models.Blog
    template_name = 'blog/index.html'
    context_object_name = 'blog_list'
    paginate_by = 10
    def get_context_data(self, **kwargs):
        context = super(indexview, self).get_context_data(**kwargs)
        pageinator = context.get('paginator')
        pageobj = context.get('page_obj')
        is_paginated = context.get('is_paginated')
        show_pagenumber = 7
        page_date = self.get_page_data(is_paginated, pageinator, pageobj, show_pagenumber)
        context.update(page_date)
        context['tabname'] = 'firsttab'
        return context

    def get_page_data(self, is_pageinated, paginator, pageobj, show_pagenumber):
        if not is_pageinated:
            return {}
        left = []
        right = []
        cur_page = pageobj.number
        total = paginator.num_pages
        half = show_pagenumber//2

        for i in range(cur_page - half, cur_page):
            if i >= 1:
                left.append(i)
        for i in range(cur_page+1, cur_page+half+1):
            if i <= total:
                right.append(i)
        page_data = {
            'left': left,
            'right': right,
        }

        return page_data

class authorindex(ListView):
    model = models.Blog
    template_name = 'blog/index.html'
    context_object_name = 'blog_list'

    def get_queryset(self):
        user = get_object_or_404(models.loguser, pk=self.kwargs.get('id'))
        return super(authorindex, self).get_queryset().filter(author=user).order_by('-created_time')

    def get_context_data(self, **kwargs):
        context = super(authorindex, self).get_context_data(**kwargs)
        context['tabname'] = 'firsttab'

        return context


class blogdetailview(DetailView):
    models = models.Blog
    template_name = 'blog/detail.html'
    context_object_name = 'blog'
    pk_url_kwarg = 'pk'

    def get_queryset(self):
        return models.Blog.objects.all()

    def get_object(self, queryset=None):
        blog = super(blogdetailview, self).get_object(queryset=None)
        blog.increase_views()
        return blog

    def get_context_data(self, **kwargs):
        context = super(blogdetailview, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list
        })
        return context

test_blog/templates/blog/detail.html
<!--　继承于母版文件-->
{% extends 'base.html' %}
{% block main %}
<article class="blog blog-{{ blog.pk }}">
    <header class="entry-header">
        <h1 class="entry-title">{{ blog.title }}</h1>
        <div class="entry-meta-detail">
            <!--　用5个<span>标签显示文章类别、发布时间、作者、评论数、阅读数-->
            <span class="blog-category">
                <a href="#">{{ blog.category.name }}</a>
            </span>
            <span class="blog-date">
                <a href="#"><time class="entry-date"datetime="{{blog.created_time }}">{{ blog.created_time }}</time></a>
            </span>
            <span class="blog-author"><a href="#">{{ blog.author.nikename }}</a></span>
            <span class="comments-link"><a href="#">共 <span>{{ comment_list | length }}</span> 条评论</a></span>
            <span class="views-count"><a href="#">{{ blog.views }} 阅读</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        <!--　文章内容，用safe过滤器防止文章的样式被转义-->
        {{ blog.body| safe }}
    </div>
</article>
<!--　判断用户是否登录，用户登录后才可以发表评论-->
{% if request.user.username %}
<section class="comment-area">
    <h3>发表评论</h3>
    <hr>
    <!--　页面表单，{% url 'comments:blog_comment' blog.pk %}反向解析成 URL， blog.pk 作为参数传给URL表达式-->
    <form action="{% url 'comments:blog_comment' blog.pk %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label class="col-md-2">名字：</label>
            {{ request.user.nikename }}
        </div>
        <div class="form-group">
            <label class="col-md-2">邮箱：</label>
           {{ request.user.email }}
        </div>
        <div class="form-group">
            <label for="{{ form.text.id_for_label }}" class="col-md-2">评论：</label>
            <!--　{{ form.text }}等表单有关变量自动转换成HTML标签-->
            {{ form.text }}
            <!--　 {{ form.text.errors.0 }} 将生成表单对应字段的错误-->
            {{ form.text.errors.0 }}
        </div>
        <div class="form-group">
            <div class="col-md-offset-2">
                <button type="submit" class="btn btn-default">发表</button>
            </div>
        </div>
        {% endif %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h5>评论列表，共 <span>{{comment_list|length}}</span> 条评论</h5>
            </div>
            <div class="panel-body">
                <ul class="comment-list list-unstyled">
                    <!--　 通过for循环取出每一条记录-->
                    {% for comment in comment_list %}
                    <li>
                        <span style="color: #777;font-size: 14px;">{{ comment.name }}&nbsp;·&nbsp;</span>
                        <time style="color: #777;font-size: 14px;">{{ comment.created_time }}</time>
                        <div style="padding-top: 5px;font-size: 16px;">{{ comment.text }}</div>
                    </li>
                    {% empty %}暂无评论{% endfor %}
                </ul>
            </div>
        </div>
</section>
{% endblock main %}

test_blog/templates/blog/index.html
<!-- 指定该文件继承于base.html文件-->
{% extends 'base.html' %}
<!-- 代码只能写在main块中，也就是只有这个块的内容与母版不同，其他的内容是相同的-->
{% block main %}
<!-- 如果传入的参数error_msg有值则显示其中的内容，视图把错误信息放在这个变量中 -->
{% if error_msg %}
<p>{{ error_msg }}</p>
{% endif %}
<!-- 通过for循环从blog_list中取出每个Blog实例对象，存到blog -->
{% for blog in blog_list %}
<!-- 引用Bootstrap框架的媒体组件，这是开头-->
<div class="media">
    <div class="media-left">
        <!-- 指定单击头像重定向到的路径-->
        <a href="{% url 'blog:authorindex' blog.author.id %}">
            <!--<img>标签的src属性值，注意/media/的前缀，这个前缀会根据settings.py的配置进行解析-->
            <img class="media-object" src="/media/{{ blog.author.head_img}}" style="width:100px;height:100px;" alt="单击头像显示此作者的博客文章列表">
        </a>
    </div>
    <div class="media-body">
        <!--　指定了文章的标题，并指定单击标题重定向到的URL-->
    <h3 class="media-heading">
        <a href="{% url 'blog:detail' blog.pk %}">{{ blog.title }}</a>
    </h3>
        <!--　文章的摘要，用了safe过滤器 -->
        <p>{{ blog.excerpt|safe }}...</p>
        <div class="entry-meta">
            <!--　以下5个<span>标签分别显示文章的分类、发表时间、作者、评论数、阅读数 -->
            <span class="blog-category"><a href="#">{{ blog.category.name }}</a></span>
            <span class="blog-date">
                <a href="#">
                    <time class="entry-date" datetime="{{ blog.created_time }}">{{ blog.created_time }}</time>
                </a>
            </span>
            <span class="blog-author"><a href="#">{{ blog.author.nikename }}</a></span>
            <span class="comments-link"><a href="#">{{ blog.comment_set.count }} 评论</a></span>
            <span class="views-count"><a href="#">{{ blog.views }} 阅读</a></span>
        </div>
    </div>
    {% empty %}
    <div class="no-post">暂时还没有发布的文章！
    </div>
    {% endfor %}
    <!--　引用Bootstrap框架的媒体组件的结尾--><!--　判断是否分页-->
    {% if is_paginated %}
    <!--　引用Bootstrap框架的分页组件，分页组件开始-->
    <nav aria-label="Page navigation">
        <ul class="pagination">{% if left %}
            <li>
                <!--　上一页的URL、页码符（<<）的设置-->
                <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <!-- &laquo;在HTML文件中表示<<，是两个左角括号，为了避免与HTML符号混淆所以用字符表示-->
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% else %}
            <li class="disabled"><a href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
            {% endif %}
        <!--　把当前页码前面的页码通过循环从left变量中取出来-->
            {% for i in left %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endfor %}
            <!--　当前页URL、页码设置-->
            <li class="active">
                <a href="?page={{ page_obj.number }}">{{ page_obj.number }} <span class="sr-only">(current)</span></a>
            </li>
            {% for i in right %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endfor %}{% if right %}
            <li>
                <!-- &raquo;在HTML文件中表示>>，是两个右角括号，为了避免与HTML符号混淆所以用字符表示-->
                <a href="?page={{ page_obj.next_page_number }}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a>
            </li>
            {% else %}
            <li class="disabled"><a href="#" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
            {% endif %}
        </ul>
    </nav>
    <!--　分页组件结尾-->
    {% endif %}
    {% endblock main %}

test_blog/templates/blog/login.html
<!-- 导入静态文件服务模块 //-->
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册页面</title>
    <!--用Bootstrap框架样式 //-->
    <link href="{% static 'blog/css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="container">
    <div class="row">
        <div align="center" style="margin-top:80px">
            <h2 class="form-signin-heading">请登录</h2>
        </div>
        <!--{% url 'blog:login' %}利用模板语言反向解析URL，用URL配置的名字解析出地址//-->
        <form method="post" action="{% url 'blog:login' %}" class="form-horizontal col-md-6 col-md-offset-3 login-form" >
            <!--安全机制，防止CSRF//-->
            {% csrf_token %}
            <div class="form-group">
                <label for="username" class="col-sm-2 control-label">用户名</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="username"name="username" placeholder="用户名">
                </div>
            </div>
            <div class="form-group">
                <label for="password" class="col-sm-2 control-label">密码</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" id="password"name="password"placeholder="密码">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
                    <!--{{ error }}显示错误信息，错误信息的内容由视图函数传递过来的//-->
                    <span style="color:red">{{ error }}</span>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- /container -->
<script src="{% static 'blog/js/jquery.js' %}"></script>
<script src="{% static 'blog/js/bootstrap.min.js'%}"></script>
</body>
</html>

test_blog/templates/blog/registe.html
<!--加载静态文件 //-->
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册页面</title>
    <!--用Bootstrap框架样式 //-->
    <link href="{% static 'blog/css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <!--应用Bootstrap页头组件 //--><!--页头组件开始 //-->
            <div class="page-header">
                <h2>用户注册<small>&nbsp;Blog注册页面</small></h2>
            </div>
            <!--页头组件结束 //-->
            <!--<form>标签设置novalidate，让前端页面表单不对输入的字段值进行验证。
            设置enctype="multipart/form-data"，表单才能支持图片、文件上传。
            class="form-horizontal"将表单设置为form-horizontal样式类，可以将字段名（<label>标签）和字段输入框水平并排布局。 //-->
            <form novalidate action="/registe/" method="post" class="form-horizontal" enctype="multipart/form-data">
                <!--Django为了防止CSRF，引入csrf_token变量随机生成token//-->
                {% csrf_token %}
                <div class="form-group">
<!--     {{ formobj.username.id_for_label }}生成一个字符串与 {{ formobj.username }}生成标签id值是一样，-->
<!--    <label>标签的for属性作用是单击这个<label>，id值与for值相同的输入框（如<input>标签）将获得焦点 //-->
                    <label for="{{ formobj.username.id_for_label }}" class="col-sm-2 control-label">{{ formobj.username.label }}</label>
                    <div class="col-sm-8">
                        <!-- {{ formobj.username }}将生成<input type="text" name="username" class="form-control" maxlength="20"…>标签，
                        该标签的许多属性是在 class reg_form(forms.Form)类中对字段进行设定的，如name、type、class等属性//-->
                        {{ formobj.username }}
                        <!-- 如果输入值校验不通过，{{ formobj.username.errors.0 }}变量返回 username字段的第一个错误信息//-->
                        <span class="help-block">{{ formobj.username.errors.0 }}</span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="{{ formobj.password.id_for_label }}" class="col-sm-2 control-label">{{ formobj.password.label }}</label>
                    <div class="col-sm-8">{{ formobj.password }}<span class="help-block">{{ formobj.password.errors.0 }}</span></div>
                </div>
                <div class="form-group">
                    <label for="{{ formobj.repassword.id_for_label }}" class="col-sm-2 control-label">{{formobj.repassword.label }}</label>
                    <div class="col-sm-8">{{ formobj.repassword }}<span class="help-block">{{ formobj.repassword.errors.0 }}</span></div>
                </div>
                <div class="form-group">
                    <label for="{{ formobj.nikename.id_for_label }}" class="col-sm-2 control-label">{{formobj.nikename.label }}</label>
                    <div class="col-sm-8">{{ formobj.nikename }}<span class="help-block">{{ formobj.nikename.errors.0 }}</span></div>
                </div>
                <div class="form-group">
                    <label for="{{ formobj.email.id_for_label }}" class="col-sm-2 control-label">{{formobj.email.label }}</label>
                    <div class="col-sm-8">{{ formobj.email }}<span class="help-block">{{ formobj.email.errors.0 }}</span></div>
                </div>
                <div class="form-group">
                    <label for="{{ formobj.telephone.id_for_label }}"class="col-sm-2 control-label">{{formobj.telephone.label }}</label>
                    <div class="col-sm-8">{{ formobj.telephone }}<span class="help-block">{{ formobj.telephone.errors.0 }}</span></div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">{{ formobj.head_img.label }}</label>
                    <div class="col-sm-8">
                        <!--在<label>标签中间加一个<img>标签，<label>标签的位置会显示一张图片，
                        <label>标签for属性值是{{ formobj.head_img.id_for_label}}产生的标签<input type="file"…>的id值，
                        该标签设置成了不可见，产生的效果就是单击图片弹出“打开”窗口 //-->
                        <label for="{{ formobj.head_img.id_for_label }}"class="col-sm-2 control-label">
<!--                             <image>标签的src属性先指向一个默认图片地址 //-->
                            <img id="head-img" src="/static/blog/image/headimg.jpg" style="height:100px;width:100px;">
                        </label>
                        {{ formobj.head_img }}
                        <span class="help-block"></span>
                    </div>
                </div>
                <div class="form-group"><div class="col-sm-offset-2 col-sm-10">
                    <input type="submit" class="btn btn-success" value="用户注册">
                    <a href="/" class="btn btn-success">返回首页</a>
                </div>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Bootstrap框架用到j Query，因此先引用j Query脚本文件 //-->
<script src="{% static 'blog/js/jquery.js' %}"></script>
<script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
<script>
    // 由于上传后的文件在提交之前并没有src指向它，所以在提交之前是不可见的
    // 以下的脚本代码通过一个文件读写对象把图片读到页面内存中
    // 并以URL形式放在对象的result属性中
    // 然后设置图片src指向这个result属性值
    // 找到头像的<input>标签并绑定change事件
    $("#id_head_img").change(function () {
        // 创建一个读取文件的对象
        var filerd = new FileReader();
        // 读取你选中的那个文件
        filerd.readAsDataURL(this.files[0]);
        // filerd.onload设置文件读取完成后的后续动作
        filerd.onload = function () {
        // 把图片加载到<img>标签的src属性上
        $("#head-img").attr("src", filerd.result);
        };
    });
</script>
</body>
</html>

test_blog/templates/blog/test_ckeditor_front.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>测试前端页面使用django-ckeditor</title>
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <script src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <script>
    CKEDITOR.env.isCompatible = true;
    </script>
</head>
<body>
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <form action="" novalidate method="post" class="form-horizontal" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title" class="col-sm-2 control-label">文章标题</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="title" name="title" value="{{ blog.title }}">
                    </div>
                </div>
                <div class="from-group">
                    <label for="body" class="col-sm-2 control-label">文章内容</label>
                    <div class="col-sm-10">
                        <textarea id="body" name="body">{{ blog.body }}</textarea>
                        <script>
                            CKEDITOR.replace('body', {
                                width:860,
                                height:600,
                                filebrowserBrowseUrl: '/ckeditor/browse/',
                                filebrowserUploadUrl: '/ckeditor/upload'
                            });
                        </script>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <script src="{% static 'blog/js/jquery.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
</body>
</html>